### ISSUE TITLE
LICENSE issue

### ISSUE THREAD

**Issue by lacabra** [team-asr/od-CAD#1]
Similar to team-asr/od-data#3:

If most of the contents of this repo is around data, I would highly encourage you to consider a more appropriate open license for data, instead of the software license you are currently chosen (or include both, one for the software components, and one for the data components). Follow this link for additional guidance on open data licenses:
https://opendefinition.org/licenses/

Also, as a best practice, in addition to mentioning the licensing terms in your README, it is recommended that you include the license on a separate file in your repository which helps GitHub detect the license automatically, and both display it more prominently but also return your project when anyone searches for projects with your specific license, which ultimately increases the visibility of your project in the open source community.

For more information see:
https://help.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository

**Comment by gichangA** [comment]
Updated licensing. 

Thank you.
